"""AI-generated audio detection module.

Identifies audio generated by AI systems (TTS, voice cloning, music generation)
by analyzing statistical fingerprints and synthesis artifacts distinct from
natural audio recordings.
"""

from typing import Dict, Any, List, Optional

import numpy as np
import librosa
from scipy import signal as scipy_signal
from scipy.stats import kurtosis, skew, entropy

from utils.constants import DEFAULT_N_FFT, DEFAULT_HOP_LENGTH
from core.model_manager import get_model_manager


class AIGenerationDetector:
    """Detect AI-generated audio using multi-factor analysis.

    Detection approaches:
    1. Spectral regularity analysis (AI output tends to be too "clean")
    2. Micro-variation analysis (lack of natural jitter/shimmer)
    3. Codec artifact detection (most AI audio passes through neural vocoders)
    4. Long-range dependency analysis
    5. AI model-based classification (when available)
    """

    def __init__(self, y: np.ndarray, sr: int):
        self.y = y
        self.sr = sr
        self._manager = get_model_manager()

    def detect(self) -> Dict[str, Any]:
        """Run full AI generation detection.

        Returns:
            Dictionary with detection scores, verdict, and evidence.
        """
        spectral = self._spectral_regularity_analysis()
        micro = self._micro_variation_analysis()
        codec = self._codec_artifact_analysis()
        longrange = self._long_range_analysis()

        # Speaker embedding analysis (uses Wespeaker)
        embedding_analysis = self._embedding_naturalness_analysis()

        # Try AI model
        model_result = self._run_model_detection()

        scores = {
            "频谱规律性": spectral["score"],
            "微变化分析": micro["score"],
            "编解码器伪影": codec["score"],
            "长程依赖": longrange["score"],
        }

        if embedding_analysis:
            scores["嵌入自然度"] = embedding_analysis["score"]

        if model_result:
            scores["AI模型"] = model_result["score"]

        # Weighted average
        if model_result:
            weights = {"频谱规律性": 0.10, "微变化分析": 0.10,
                       "编解码器伪影": 0.08, "长程依赖": 0.08,
                       "嵌入自然度": 0.14, "AI模型": 0.50}
        elif embedding_analysis:
            weights = {"频谱规律性": 0.25, "微变化分析": 0.25,
                       "编解码器伪影": 0.15, "长程依赖": 0.15,
                       "嵌入自然度": 0.20}
        else:
            weights = {"频谱规律性": 0.3, "微变化分析": 0.3,
                       "编解码器伪影": 0.2, "长程依赖": 0.2}

        final_score = sum(scores.get(k, 0) * weights.get(k, 0) for k in weights if k in scores)

        # Verdict
        if final_score > 0.7:
            verdict = "AI生成"
            desc = "多项指标强烈指向该音频为 AI 系统生成（TTS/语音克隆/AI音乐生成）。"
            confidence = "高"
        elif final_score > 0.5:
            verdict = "疑似AI生成"
            desc = "部分指标异常，该音频可能由 AI 系统生成或经过 AI 处理。"
            confidence = "中"
        elif final_score > 0.3:
            verdict = "不确定"
            desc = "存在少量异常指标，但不足以确定为 AI 生成。可能为高质量录音或轻度处理。"
            confidence = "低"
        else:
            verdict = "自然录音"
            desc = "音频特征符合自然录音规律，未检测到 AI 生成的典型指纹。"
            confidence = "高"

        # Collect all indicators
        all_indicators = []
        for detail in [spectral, micro, codec, longrange]:
            all_indicators.extend(detail.get("indicators", []))
        if embedding_analysis:
            all_indicators.extend(embedding_analysis.get("indicators", []))
        if model_result:
            all_indicators.extend(model_result.get("indicators", []))

        return {
            "final_score": float(final_score),
            "verdict": verdict,
            "verdict_description": desc,
            "confidence": confidence,
            "scores": {k: float(v) for k, v in scores.items()},
            "indicators": all_indicators,
            "details": {
                "spectral_regularity": spectral,
                "micro_variation": micro,
                "codec_artifacts": codec,
                "long_range": longrange,
                "ai_model": model_result,
            },
            "model_used": model_result is not None,
        }

    def _spectral_regularity_analysis(self) -> Dict[str, Any]:
        """AI audio tends to have overly regular spectral characteristics."""
        indicators = []
        score = 0.0

        S = np.abs(librosa.stft(self.y, n_fft=DEFAULT_N_FFT, hop_length=DEFAULT_HOP_LENGTH))
        S_db = librosa.amplitude_to_db(S, ref=np.max)

        # 1. Frame-to-frame spectral variation
        frame_diffs = np.mean(np.abs(np.diff(S_db, axis=1)), axis=0)
        variation_cv = np.std(frame_diffs) / (np.mean(frame_diffs) + 1e-10)

        if variation_cv < 0.3:
            score += 0.3
            indicators.append("频谱帧间变化过于均匀（AI生成的典型特征）")
        elif variation_cv < 0.5:
            score += 0.15
            indicators.append("频谱变化较为规律")

        # 2. Spectral entropy over time
        spec_entropy = []
        for i in range(S.shape[1]):
            frame = S[:, i]
            frame_norm = frame / (np.sum(frame) + 1e-10)
            spec_entropy.append(entropy(frame_norm + 1e-10))

        entropy_var = np.var(spec_entropy)
        if entropy_var < 0.01:
            score += 0.25
            indicators.append("频谱熵变化极小（合成信号特征）")

        # 3. Sub-band energy consistency
        n_bands = 8
        band_size = S.shape[0] // n_bands
        band_variances = []
        for b in range(n_bands):
            band = S[b * band_size:(b + 1) * band_size, :]
            band_variances.append(np.var(np.mean(band, axis=0)))

        band_var_ratio = np.min(band_variances) / (np.max(band_variances) + 1e-10)
        if band_var_ratio > 0.7:
            score += 0.2
            indicators.append("各频带能量变化过于一致")

        if not indicators:
            indicators.append("频谱规律性正常")

        return {"score": min(1.0, score), "indicators": indicators}

    def _micro_variation_analysis(self) -> Dict[str, Any]:
        """Natural speech has micro-variations (jitter, shimmer) that AI often lacks."""
        indicators = []
        score = 0.0

        hop = DEFAULT_HOP_LENGTH

        # 1. Jitter analysis (pitch period variation)
        f0, voiced, _ = librosa.pyin(self.y, fmin=50, fmax=500, sr=self.sr, hop_length=hop)
        if np.any(voiced):
            f0_valid = f0[voiced]
            if len(f0_valid) > 10:
                # Jitter: variation in consecutive pitch periods
                periods = 1.0 / (f0_valid + 1e-10)
                jitter = np.mean(np.abs(np.diff(periods))) / (np.mean(periods) + 1e-10)

                if jitter < 0.005:
                    score += 0.3
                    indicators.append(f"基频抖动 (jitter) 极低 ({jitter:.5f})，缺乏自然微变化")
                elif jitter < 0.01:
                    score += 0.15
                    indicators.append(f"基频抖动偏低 ({jitter:.5f})")

                # Shimmer: amplitude variation
                rms = librosa.feature.rms(y=self.y, hop_length=hop)[0]
                rms_voiced = rms[:len(voiced)][voiced]
                if len(rms_voiced) > 10:
                    shimmer = np.mean(np.abs(np.diff(rms_voiced))) / (np.mean(rms_voiced) + 1e-10)
                    if shimmer < 0.02:
                        score += 0.25
                        indicators.append(f"振幅微变化 (shimmer) 极低 ({shimmer:.5f})")

        # 2. High-frequency micro-texture
        # Natural audio has complex high-freq texture; AI is often smoother
        if self.sr > 8000:
            nyq = self.sr / 2
            high_pass = 4000 / nyq
            b, a = scipy_signal.butter(4, high_pass, btype='high')
            hf = scipy_signal.filtfilt(b, a, self.y)
            hf_entropy = entropy(np.histogram(hf, bins=100)[0] + 1)
            if hf_entropy < 3.0:
                score += 0.2
                indicators.append("高频微纹理信息不足（AI生成音频常见特征）")

        # 3. Attack transient analysis
        onset_frames = librosa.onset.onset_detect(y=self.y, sr=self.sr, hop_length=hop)
        if len(onset_frames) > 2:
            onset_strengths = librosa.onset.onset_strength(y=self.y, sr=self.sr, hop_length=hop)
            onset_var = np.std(onset_strengths[onset_frames]) / (np.mean(onset_strengths[onset_frames]) + 1e-10)
            if onset_var < 0.3:
                score += 0.2
                indicators.append("起音特征过于一致（缺乏自然发音变化）")

        if not indicators:
            indicators.append("微变化特征正常")

        return {"score": min(1.0, score), "indicators": indicators}

    def _codec_artifact_analysis(self) -> Dict[str, Any]:
        """Detect neural vocoder artifacts."""
        indicators = []
        score = 0.0

        S = np.abs(librosa.stft(self.y, n_fft=4096, hop_length=512))

        # 1. Check for band-limited output (common in vocoders)
        freq_axis = np.fft.rfftfreq(4096, d=1.0 / self.sr)
        energy_by_freq = np.mean(S, axis=1)

        # Find effective bandwidth
        total_energy = np.sum(energy_by_freq)
        cumulative = np.cumsum(energy_by_freq) / (total_energy + 1e-10)
        bw_99 = freq_axis[np.searchsorted(cumulative, 0.99)] if len(freq_axis) > 0 else self.sr / 2

        max_expected = self.sr / 2 * 0.9
        if bw_99 < max_expected * 0.6:
            score += 0.3
            indicators.append(f"有效带宽仅 {bw_99:.0f} Hz（预期 {max_expected:.0f} Hz），可能经过声码器处理")

        # 2. Check for checkerboard artifacts in spectrogram
        S_small = S[:S.shape[0] // 2, :]  # lower half
        if S_small.shape[1] > 10:
            # Look for alternating patterns
            row_diffs = np.diff(S_small, axis=0)
            checkerboard_score = np.mean(np.abs(np.diff(np.sign(row_diffs), axis=1)))
            if checkerboard_score > 1.5:
                score += 0.2
                indicators.append("检测到频谱棋盘状伪影（声码器特征）")

        # 3. Phase coherence (vocoders often have unnatural phase)
        S_complex = librosa.stft(self.y, n_fft=DEFAULT_N_FFT, hop_length=DEFAULT_HOP_LENGTH)
        phase = np.angle(S_complex)
        group_delay = -np.diff(phase, axis=1)
        gd_var = np.var(group_delay)

        if gd_var < 0.5:
            score += 0.25
            indicators.append("群延迟过于一致（自然信号应有更大变化）")

        if not indicators:
            indicators.append("未检测到明显的编解码器伪影")

        return {"score": min(1.0, score), "indicators": indicators}

    def _long_range_analysis(self) -> Dict[str, Any]:
        """Analyze long-range temporal dependencies."""
        indicators = []
        score = 0.0

        # 1. Long-term spectral variation
        hop = DEFAULT_HOP_LENGTH
        mfcc = librosa.feature.mfcc(y=self.y, sr=self.sr, n_mfcc=13, hop_length=hop)

        # Compute self-similarity matrix on downsampled MFCC
        step = max(1, mfcc.shape[1] // 100)
        mfcc_ds = mfcc[:, ::step]

        if mfcc_ds.shape[1] > 10:
            from sklearn.metrics.pairwise import cosine_similarity
            sim_matrix = cosine_similarity(mfcc_ds.T)

            # Check for overly repetitive patterns
            off_diagonal = sim_matrix[np.triu_indices_from(sim_matrix, k=5)]
            mean_sim = np.mean(off_diagonal)

            if mean_sim > 0.95:
                score += 0.35
                indicators.append(f"长时自相似度过高 ({mean_sim:.3f})，音频内容重复性异常")
            elif mean_sim > 0.9:
                score += 0.2
                indicators.append(f"长时自相似度偏高 ({mean_sim:.3f})")

        # 2. Spectral flux consistency over long periods
        S = np.abs(librosa.stft(self.y, n_fft=DEFAULT_N_FFT, hop_length=hop))
        flux = np.sum(np.maximum(0, np.diff(S, axis=1)), axis=0)

        if len(flux) > 50:
            # Divide into long windows and compare statistics
            n_windows = min(10, len(flux) // 10)
            window_size = len(flux) // n_windows
            window_means = [np.mean(flux[i * window_size:(i + 1) * window_size])
                           for i in range(n_windows)]
            window_cv = np.std(window_means) / (np.mean(window_means) + 1e-10)

            if window_cv < 0.1:
                score += 0.3
                indicators.append("长时频谱通量过于稳定（缺乏自然语音的段落变化）")

        if not indicators:
            indicators.append("长时依赖性特征正常")

        return {"score": min(1.0, score), "indicators": indicators}

    def _embedding_naturalness_analysis(self) -> Optional[Dict[str, Any]]:
        """Analyze speaker embedding patterns for AI generation artifacts.
        
        AI-generated audio often shows:
        - Unnaturally uniform embeddings across segments
        - Lack of natural micro-variation in speaker characteristics
        - Unusual embedding space distribution
        """
        try:
            from core.model_integration import SpeakerEmbedder
            embedder = SpeakerEmbedder()
        except Exception:
            return None
        
        indicators = []
        score = 0.0
        
        segment_dur = 1.5
        segment_samples = int(segment_dur * self.sr)
        hop_samples = int(1.0 * self.sr)
        
        if len(self.y) < segment_samples * 3:
            return None
        
        embeddings = []
        for start in range(0, len(self.y) - segment_samples, hop_samples):
            segment = self.y[start:start + segment_samples]
            if np.max(np.abs(segment)) < 0.01:
                continue
            try:
                emb = embedder.extract_embedding(segment, self.sr)
                embeddings.append(emb)
            except Exception:
                continue
        
        if len(embeddings) < 4:
            return None
        
        embeddings = np.array(embeddings)
        
        # 1. Inter-segment similarity (AI tends to be too uniform)
        sims = []
        for i in range(len(embeddings) - 1):
            sim = float(np.dot(embeddings[i], embeddings[i + 1]))
            sims.append(sim)
        
        mean_sim = np.mean(sims)
        sim_variance = np.var(sims)
        
        # AI-generated: very high mean similarity + very low variance
        if mean_sim > 0.97 and sim_variance < 0.001:
            score += 0.4
            indicators.append(f"片段嵌入过度一致 (均值={mean_sim:.3f}, 方差={sim_variance:.5f}) — AI生成特征")
        elif mean_sim > 0.94 and sim_variance < 0.003:
            score += 0.2
            indicators.append(f"片段嵌入一致性偏高 (均值={mean_sim:.3f})")
        
        # 2. Embedding entropy (diversity of dimensions)
        # AI audio often has lower-rank embeddings
        embedding_mean = np.mean(embeddings, axis=0)
        centered = embeddings - embedding_mean
        
        # Singular value analysis
        try:
            _, s, _ = np.linalg.svd(centered, full_matrices=False)
            s_normalized = s / (np.sum(s) + 1e-10)
            effective_rank = np.exp(-np.sum(s_normalized * np.log(s_normalized + 1e-10)))
            
            # AI-generated audio tends to have lower effective rank
            if effective_rank < 2.0:
                score += 0.3
                indicators.append(f"嵌入空间有效秩过低 ({effective_rank:.1f}) — 可能为AI合成")
            elif effective_rank < 3.0:
                score += 0.15
                indicators.append(f"嵌入空间有效秩偏低 ({effective_rank:.1f})")
        except Exception:
            pass
        
        # 3. Frame-level smoothness (AI is often unnaturally smooth)
        diffs = np.array([np.linalg.norm(embeddings[i+1] - embeddings[i]) 
                         for i in range(len(embeddings) - 1)])
        diff_cv = np.std(diffs) / (np.mean(diffs) + 1e-10)  # coefficient of variation
        
        if diff_cv < 0.1 and np.mean(diffs) < 0.05:
            score += 0.2
            indicators.append(f"嵌入变化过于平滑 (变异系数={diff_cv:.3f}) — AI生成特征")
        
        score = min(1.0, score)
        
        if not indicators:
            indicators.append(f"嵌入自然度正常 (相似度={mean_sim:.3f}, 变异系数={diff_cv:.3f})")
        
        return {
            "score": score,
            "indicators": indicators,
            "mean_similarity": float(mean_sim),
            "sim_variance": float(sim_variance),
            "num_segments": len(embeddings),
            "model": "Wespeaker ResNet34",
        }

    def _run_model_detection(self) -> Optional[Dict[str, Any]]:
        """Run AI model for AI-generation detection if available."""
        # Use AASIST model (anti-spoofing detects both deepfake and AI-generated)
        try:
            import onnxruntime as ort
            from pathlib import Path
            import os
            
            candidates = [
                Path(__file__).parent.parent / "models" / "aasist" / "aasist_antispoof.onnx",
                Path(os.getcwd()) / "models" / "aasist" / "aasist_antispoof.onnx",
            ]
            
            model_path = None
            for p in candidates:
                if p.exists():
                    model_path = str(p)
                    break
            
            if model_path:
                session = ort.InferenceSession(model_path, providers=['CPUExecutionProvider'])
                
                if self.sr != 16000:
                    y_16k = librosa.resample(self.y, orig_sr=self.sr, target_sr=16000)
                else:
                    y_16k = self.y.copy()
                
                if np.max(np.abs(y_16k)) > 0:
                    y_16k = y_16k / np.max(np.abs(y_16k))
                
                target_len = 64000
                if len(y_16k) > target_len:
                    y_16k = y_16k[:target_len]
                else:
                    y_16k = np.pad(y_16k, (0, target_len - len(y_16k)))
                
                audio_input = y_16k.reshape(1, 1, -1).astype(np.float32)
                result = session.run(None, {"audio": audio_input})
                ai_prob = float(result[0].flatten()[0])
                
                return {
                    "score": ai_prob,
                    "model_name": "AASIST Anti-Spoofing",
                    "indicators": [f"AASIST 模型AI生成概率: {ai_prob:.3f}"],
                }
        except Exception:
            pass
        
        # Fallback to model_manager
        if not self._manager.has_onnx_runtime:
            return None

        session = self._manager.load_onnx_model("ai_generation_detector")
        if session is None:
            return None

        try:
            if self.sr != 16000:
                y_16k = librosa.resample(self.y, orig_sr=self.sr, target_sr=16000)
            else:
                y_16k = self.y

            max_len = 16000 * 10
            if len(y_16k) > max_len:
                y_16k = y_16k[:max_len]
            else:
                y_16k = np.pad(y_16k, (0, max_len - len(y_16k)))

            inputs = {"input": y_16k.reshape(1, -1).astype(np.float32)}
            results = self._manager.run_inference("ai_generation_detector", inputs)

            if results:
                output = list(results.values())[0].flatten()
                ai_prob = float(output[0]) if len(output) > 0 else 0.5
                return {
                    "score": ai_prob,
                    "model_name": "ai_generation_detector",
                    "indicators": [f"AI 模型评分: {ai_prob:.3f}"],
                }
        except Exception:
            pass
        return None
